server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere_auth
    username: postgres
    password: Anurag@2403

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

#eureka:
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka